### ISSUE TITLE
Rebrand site/mailing list 

### ISSUE THREAD

**Issue by pschloss** [UMCarpentries/umcarpentries.github.io#22]
To be consistent with the parent organization, we probably want to brand ourselves as "UM Carpentries" rather than "UM SWC" (see also  UMSWC/curriculum#18)

**Comment by kelly-sovacool** [comment]
Suggest "U-M Carpentries" -- I think having the hyphen is consistent with the branding guidelines https://brand.umich.edu/editorial-resources/abbreviations/

**Comment by kelly-sovacool** [comment]
Thanks Pat!
